project:
  type: website
  output-dir: docs

website:
  title: "code4research"
  sidebar:
    collapse-level: 1
    border: false
    style: "docked"
    search: false
    contents:
      - section: Part 1
        contents:
          - text: "Introduction"
            href: existing-projects/intro.qmd
          - text: "Dependencies"
            href: existing-projects/dependencies.qmd
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - existing-projects/testing.qmd


format:
  html:
    page-layout: full
    mainfont: Space Grotesk
    theme: 
      - theme.scss
    toc: true
    footnotes-hover: true

bibliography: refs.bib
